# Generated by Django 3.1.2 on 2020-11-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSystem',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('measurement_system', models.CharField(choices=[('1', 'METRIC'), ('2', 'IMPERIAL')], default='1', max_length=8)),
            ],
        ),
    ]
