# Generated by Django 3.1.2 on 2020-11-11 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('benefit', '0002_auto_20201111_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('1', 'MALE'), ('2', 'FEMALE')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='appconfigmodel',
            name='measurement_system',
            field=models.CharField(choices=[('1', 'METRIC'), ('2', 'IMPERIAL')], default='1', max_length=1),
        ),
    ]
