# Generated by Django 3.1.2 on 2020-11-11 20:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('benefit', '0003_auto_20201111_2023'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppConfigModel',
            new_name='AppConfig',
        ),
        migrations.RenameModel(
            old_name='ProfileModel',
            new_name='Profile',
        ),
    ]
