# Generated by Django 3.1.2 on 2020-11-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefit', '0004_auto_20201111_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='measurement_system',
            field=models.CharField(choices=[('METRIC', 'Metric'), ('IMPERIAL', 'Imperial')], default='METRIC', max_length=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=6),
        ),
    ]
