# Generated by Django 3.1.2 on 2020-11-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefit', '0005_auto_20201111_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
