# Generated by Django 3.1.2 on 2020-11-11 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benefit', '0006_auto_20201111_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
